# Generated by Django 6.0 on 2025-12-20 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, max_length=12)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('colour', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=20)),
                ('reference', models.UUIDField(default=uuid.UUID('bc04efca-11cd-4203-8c29-31c7f6d31c05'), editable=False, unique=True)),
                ('percent_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, max_length=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cate_name', to='category.cateory')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='store.product')),
            ],
        ),
    ]
