# Generated by Django 6.0 on 2025-12-20 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('a9947340-46a7-457d-8d0d-463a5be867ff'), editable=False, unique=True),
        ),
    ]
