# Generated by Django 6.0 on 2025-12-27 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('07e775f7-fc89-4f75-8abe-f83d27a2c028'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='38, 39, 40, 41, 42, 43, 44, 45', max_length=200),
        ),
    ]
