# Generated by Django 6.0 on 2025-12-28 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_reference_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('c1ae835b-8126-4536-a667-f9cb357ec5ae'), editable=False, unique=True),
        ),
    ]
