# Generated by Django 6.0 on 2025-12-28 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_price_product_amount_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('5d76e9e9-0038-4d2f-bf31-8909ab6b1356'), editable=False, unique=True),
        ),
    ]
