# Generated by Django 6.0 on 2026-01-08 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('e9989185-c58b-4857-9a91-cbb76d87fdf8'), editable=False, unique=True),
        ),
    ]
